version: '3.3'

services:
  # ตั้งชื่อคอนเทนเนอร์ของ WordPress
  wordpress:
    image: wordpress:latest
    ports:
      - "8888:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 12345678
      WORDPRESS_DB_NAME: pos

  # ตั้งชื่อคอนเทนเนอร์ของ MySQL
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "9999:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pos
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678

  # ตั้งชื่อคอนเทนเนอร์ของ phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1111:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345678
